# Generated by Django 6.0.2 on 2026-02-19 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='quantity_needed',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='bags_needed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donors',
            field=models.ManyToManyField(blank=True, related_name='donations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
