# Generated by Django 6.0.2 on 2026-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_bloodrequest_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(default='Unknown Hospital', max_length=255),
        ),
    ]
