# Generated by Django 6.0.2 on 2026-02-19 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_bloodrequest_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
